# Change these first
owner: LightingControl # Your GitHub organization or username, where this repository lives
repo: devmonitor # The name of this repository

sites:
  - name: API DEV
    url: https://www.api-dev.centro.network
  - name: Frontend DEV
    url: https://www.dev.centro.network
  - name: App DEV
    url: https://www.app-dev.centro.network
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: devmon.centro.network
  baseUrl: /devmonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Centro** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
