# Change these first
owner: LightingControl # Your GitHub organization or username, where this repository lives
repo: devmonitor # The name of this repository

sites:
  - name: Frontend DEV
    url: https://main.centro.network
  - name: API DEV
    url: https://api.centro.network
  - name: App DEV
    url: https://app-dev.centro.network


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.centro.network
  #baseUrl: /devmonitor
  logoUrl: https://cms.centro.network/uploads/Centro_Doorhanger_4ca7cf39b4.png
  name: Centro Uptime
  introTitle: "**Centro** Status."
  introMessage: Centro Active Servers
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is powered by [Centro](https://centro.network)